# Generated by Django 2.2.7 on 2020-06-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='profile', verbose_name='الصورة الشخصية :'),
            preserve_default=False,
        ),
    ]
