# Generated by Django 2.2.7 on 2020-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200615_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='المحافظة :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(default='', max_length=50, verbose_name='العنوان بالتفصيل :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default=0, max_length=50, verbose_name='الهاتف :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='spacialist_doctor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متخصص في ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default='', max_length=50, verbose_name='نبذة عنك '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدة الانتظار : '),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.IntegerField(default=0, verbose_name='عدد ساات العمل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=80, verbose_name='الاسم :'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='من أنا :'),
        ),
    ]
