# Generated by Django 2.2.7 on 2020-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_join_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=50, verbose_name='الجنس :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الانضمام :'),
        ),
    ]
